/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/*.{js,ts,jsx,tsx}",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#282a2e",
        "outline-variant": "#4d4635",
        "outline": "#99907c",
        "on-error-container": "#ffdad6",
        "surface-container-highest": "#323539",
        "primary-fixed-dim": "#e9c349",
        "secondary-container": "#444954",
        "on-tertiary-fixed-variant": "#27438a",
        "on-primary-fixed": "#241a00",
        "surface-tint": "#e9c349",
        "primary": "#f2ca50",
        "surface-dim": "#111417",
        "surface-container-lowest": "#0c0e12",
        "primary-container": "#d4af37",
        "on-tertiary-container": "#254188",
        "on-surface": "#e1e2e7",
        "tertiary-fixed-dim": "#b4c5ff",
        "tertiary-container": "#97b0ff",
        "error": "#ffb4ab",
        "on-secondary-container": "#b4b8c6",
        "on-secondary-fixed-variant": "#424752",
        "secondary-fixed-dim": "#c2c6d4",
        "on-tertiary-fixed": "#00174b",
        "on-primary-container": "#554300",
        "secondary": "#c2c6d4",
        "surface-container": "#1d2023",
        "tertiary-fixed": "#dbe1ff",
        "surface": "#111417",
        "primary-fixed": "#ffe088",
        "on-background": "#e1e2e7",
        "error-container": "#93000a",
        "on-tertiary": "#082b72",
        "on-secondary": "#2b303b",
        "background": "#111417",
        "surface-container-low": "#191c1f",
        "inverse-on-surface": "#2e3134",
        "on-primary": "#3c2f00",
        "tertiary": "#bfcdff",
        "inverse-surface": "#e1e2e7",
        "on-secondary-fixed": "#171c25",
        "inverse-primary": "#735c00",
        "surface-variant": "#323539",
        "surface-bright": "#37393d",
        "on-surface-variant": "#d0c5af",
        "on-primary-fixed-variant": "#574500",
        "secondary-fixed": "#dee2f0",
        "on-error": "#690005"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      fontFamily: {
        headline: ["Manrope"],
        body: ["Inter"],
        label: ["Inter"]
      }
    },
  },
  plugins: [],
}