"""Numero du candidat

Revision ID: 40da3765b7dc
Revises: 
Create Date: 2026-04-13 11:48:04.014505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40da3765b7dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('number', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_vote_device'), 'vote_logs', type_='unique')
    op.create_unique_constraint('uq_candidate_ip_ua', 'vote_logs', ['candidate_id', 'ip', 'user_agent'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_candidate_ip_ua', 'vote_logs', type_='unique')
    op.create_unique_constraint(op.f('uq_vote_device'), 'vote_logs', ['ip', 'user_agent'])
    op.drop_column('candidates', 'number')
    # ### end Alembic commands ###
